sudo: false
os: linux
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
