name: Check ABI for Electron Version

on:
  workflow_dispatch:
    inputs:
      electron-version:
        type: string
        description: Electron version to check (e.g. 26.0.0)
        required: true
      expected-abi:
        type: string
        description: Expected ABI number (e.g. 117)
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: lts/*
    - name: Create a Temporary package.json
      run: npm init --yes
    - name: Install latest node-abi
      run: npm install --save-dev node-abi
    - name: Check ABI for Electron version
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        ELECTRON_VERSION: ${{ github.event.inputs.electron-version }}
        EXPECTED_ABI: ${{ github.event.inputs.expected-abi }}
      with:
        script: |
          const { getAbi } = await import('${{ github.workspace }}/node_modules/node-abi/index.js');

          const abi = getAbi(process.env.ELECTRON_VERSION, 'electron');

          if (abi !== process.env.EXPECTED_ABI) {
            core.error(`Got ABI ${abi}, expected ${process.env.EXPECTED_ABI}`);
            process.exitCode = 1;
          } else {
            core.info(`Got expected ABI ${abi}`);
          }
