name: Release

on:
  push:
    branches:
      - main
      - 3-x-y

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    environment: npm
    permissions:
      id-token: write # for publishing releases
      contents: write # for making github release
      pull-requests: write # for commenting release version
      issues: write # for commenting release version
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24.x'
      - name: Update npm to version that supports trusted publishing
        run: npm install -g npm@^11.5.1
      - name: Install
        run: yarn install --immutable
      - name: Fetch NPM Token
        uses: electron/npm-trusted-auth-action@418d14975a3ff06683cc4580a4eba437f0f017f1 # v1.0.0
        with:
          package-name: node-abi
      - name: Run semantic release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
